language: php
php:
- '5.5'
git:
  depth: 3

cache:
  directories:
    - node_modules

branches:
  only:
  - master

services:
- mysql

env:
- DEPLOY_USER=fodor DEPLOY_HOST=fodor.xyz DEPLOY_PATH=/var/www/

install:
- npm install -g npm@2
- composer install
- npm install
- mysql -e "create database IF NOT EXISTS fodor;" -uroot
- mysql -e "grant all on fodor.* to 'fodor'@'127.0.0.1' identified by 'fodorsecret';"
  -uroot
- mysql -e "grant all on fodor.* to 'fodor'@'localhost' identified by 'fodorsecret';"
  -uroot
- node_modules/.bin/gulp
- php artisan migrate --force
- php artisan key:generate

after_success:
- export DATETIME=`date +%Y%m%d%H%M%S`
- mkdir $DATETIME
- mv * $DATETIME
- tar --exclude=node_modules -czf package.tgz $DATETIME
- chmod 600 $DATETIME/tmp/fodor-travis
- scp -i $DATETIME/tmp/fodor-travis -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
- scp -i $DATETIME/tmp/fodor-travis -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $DATETIME/bin/deploy.sh $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
- ssh -i $DATETIME/tmp/fodor-travis -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "/bin/bash $DEPLOY_PATH/deploy.sh ${DATETIME}"
- rm -rf $DATETIME/tmp

before_install:
- mkdir tmp
- openssl aes-256-cbc -K $encrypted_fabbc996a929_key -iv $encrypted_fabbc996a929_iv -in fodor-travis.enc -out tmp/fodor-travis -d
- openssl aes-256-cbc -K $encrypted_fabbc996a929_key -iv $encrypted_fabbc996a929_iv -in .env.enc -out .env -d

