language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'

services:
  - mysql

before_install:
  - composer install
  - cp .env.example .env
  - mysql -e "create database IF NOT EXISTS fodor;" -uroot
  - mysql -e "grant all on fodor.* to 'fodor'@'127.0.0.1' identified by 'fodorsecret';" -uroot
  - mysql -e "grant all on fodor.* to 'fodor'@'localhost' identified by 'fodorsecret';" -uroot
  - php artisan migrate --force
  - php artisan key:generate

